### ISSUE TITLE
Interface development.

### ISSUE THREAD

**Issue by martinreycristina** [Arquisoft/dechat_es5b#41]
We'll need a nice user interface for the end user.

**Comment by martinreycristina** [comment]
![Two-people chat view](https://lh3.googleusercontent.com/F86MGQ7GQ8amGw1IHN1NR5OZVFEY_MXV5ApuPZ1_uSNfxcJe9YDGSJ7NXVrJFemRv9zN8UrAoF6Czvd_h-6U3ns20y0tJ98APwAyjwamuKBG7fou69tVuCnyQcbUoRnH8OU5kN2Qi1QZp8t6gduAjjsj9pWw5SZpHWWheYRFhsvKr61zwz4CZw-dBXUg7GUPNViWWZyJrnaZAvhyFg5vdLNnE7APlh9gGoH8rKeZQHXXyNv1jfd_fwd3GSZsD1_z_4KnlbPgCESJyzRuBvA9r_rZFMLu4NSxd-8gICrCWtSJwFu6LtgUVWmLDqNwAPW3TYh6EwlrlZYZYC1ho9d-5U85nuTT9DqmOjG70Fc3xlwXLps6PJd8vsGkmoeORnBL-5o6qWcp73sohUaqsIyt_wCu8bMz0xi88O586o6tEoVYLuAjPHF1l07_YGEyz8qTzLO__1B8zsDsmjesD2CfOI7P_hpEtTUvRrS9pdtpFCNrAT_bSAYm67Ix1T1zFnFaivdv52Lz0QKv4_WqnAcieEEGoJqKJSEMKLPFzcvy6i5nr9fuAuNDAxvftl1DFsVEoVMHL8Dz8o5FtBeXQroWHA8lYJTPjcmE6wxu6WY=w1920-h903)

**Comment by ghost** [comment]
Login interface done. 3aab3199e55cdc42e1383356901340d2b31a82f9

**Comment by ghost** [comment]
@SrCharlystar When you can, please check the navigation bar, I couldn't center the text "dechates5b" vertically.

**Comment by mesacarlos** [comment]
Working on it

**Comment by ghost** [comment]
@SrCharlystar When you can, please take a look of the chat room interface to finish it with bootstrap. Its current look is identical to the home page, but I wasn't able to make the friends bar and the chat dashboard.

**Comment by mesacarlos** [comment]
Working now on it

**Comment by mesacarlos** [comment]
Simple sidebar added. Pending changes:

- Adapt select element to sidebar: Not done because it may be better to change from select box to links (or buttons with link appareance). This can be implemented by using:

1. [A list group](https://getbootstrap.com/docs/4.0/components/list-group/): The simple solution, and maybe the best. Just a couple of links in a group that can toggle a visual indicator that shows in which chat are you at the moment.

1. [Navs](https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior): This would be a good solution if we decided to preload all chats and just hide-unhide them with user interaction. This Navs automatically hide and shows containers. It requires bootstrap JS libraries. I personally do no think this is a good solution because preloading a lot of chats can end up in high memmory and network usage.

- Message listing: At the moment, UI branch has not implemented message retrieving. Waiting backend team to finish this implementation.

**EDIT: Bootstrap references that may help when creating chat UI:**

1. Message containers with image, Name of sender (and date, POD, etc..) and message [using BootStrap Media objects](https://getbootstrap.com/docs/4.3/components/media-object/)
![Shadow image](https://i.imgur.com/2fludof.png?)

2. Message boxes float. Making own messages appear to the right and friend's messages to the left may be easier using [this float BS utility](https://getbootstrap.com/docs/4.3/utilities/float/)

3. [Message shadows](https://getbootstrap.com/docs/4.3/utilities/shadows/). Very simple shadow for message boxes.

![Shadow image](https://i.imgur.com/pJyhiJy.png?)

**Comment by ghost** [comment]
I think we can consider the interface for this release finished with a view to possible improvements for the next evaluation.
Just ask if it would be possible to adjust the friends sidebar to the whole page to avoid the space that appears in the image. 
I tried to fix it by changing the classes of the div element that contains the bar and adjusting the css but I wasn't able to. It is a minor visual failure without importance.
![image](https://user-images.githubusercontent.com/47207766/54236628-49b87a80-4514-11e9-9d91-4e37d31f3076.png)

**Comment by mesacarlos** [comment]
> I think we can consider the interface for this release finished with a view to possible improvements for the next evaluation.
> Just ask if it would be possible to adjust the friends sidebar to the whole page to avoid the space that appears in the image.
> I tried to fix it by changing the classes of the div element that contains the bar and adjusting the css but I wasn't able to. It is a minor visual failure without importance.
> ![image](https://user-images.githubusercontent.com/47207766/54236628-49b87a80-4514-11e9-9d91-4e37d31f3076.png)

Yes, I think that youre right. UI is finished for this release.

About that minor UI problem, I think it is now solved. Just switched sidebar and container to Bootstrap GRIDs so layout should be working fine now.

I think this new sidebar system is more maintainable than my older CSS made "a pelo"

**Comment by SrCharlystar** [comment]
Still having the above issue the problem is that navbar is not sticked to the top of the page. It can be simply solved by adding `sticky-top` to the navbar div classes.

**Comment by martinreycristina** [comment]
It would be nice to modify the people list selection to make it a little more elegant.

**Comment by mesacarlos** [comment]
Friend list selection improved, now using a list group.

**Comment by ghost** [comment]
Improvement of messages' interface in the chat room done.

**Comment by ghost** [comment]
I think the interface already looks good for the third release. It's been improved. 
I think we can finish its implementation and fix some minor bugs we find later.
